{{- if .Values.cert.enabled }}
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cnpg-database.fullname" . }}-cert
spec:
  {{- with .Values.cert.dnsNames }}
  dnsNames:
  {{- range . }}
    - {{ . }}
  {{- end }}
  {{- end }}
  {{- with .Values.cert.usages }}
  usages:
  {{- range . }}
    - {{ . }}
  {{- end }}
  {{- end }}
  {{- with .Values.cert.issuerRef }}
  issuerRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  secretName: {{ include "cnpg-database.fullname" . }}-cert
{{- end }}
