{{- if .Values.backup.enabled }}
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "cnpg-database.fullname" . }}
  {{- with .Values.backup.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  suspend: {{.Values.backup.suspend }}
  schedule: {{ .Values.backup.schedule | quote }}
  immediate: {{ .Values.backup.immediate }}
  backupOwnerReference: self
  cluster:
    name: {{ include "cnpg-database.fullname" . }}
{{- end }}
