{{- if .Values.backup.enabled }}
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/bitnami.com/sealedsecret_v1alpha1.json
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "cnpg-database.fullname" . }}-s3
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    {{- include "cnpg-database.labels" . | nindent 4 }}
spec:
  encryptedData:
    S3_ACCESS_KEY: {{.Values.backup.s3.accessKey }}
    S3_SECRET_KEY: {{.Values.backup.s3.secretKey }}
  template:
    metadata:
      annotations:
        cnpg.io/reload: "true"
{{- end }}
