name: CI

on:
  push:

jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Check out repository
        uses: bakdata/ci-templates/actions/checkout@1.69.2

      - name: Get version
        id: get-version
        shell: bash
        env:
          DEFAULT_BRANCH: refs/heads/${{ github.event.repository.default_branch }}
        run: |
          version=$(sed -n 's/^current_version = \(\.*\)/\1/p' < .bumpversion.cfg)
          if [[ "${GITHUB_REF}" != refs/tags/* ]]; then
            version="${version}-dev"
          fi
          echo "version=${version}" >> "$GITHUB_OUTPUT"

  build-and-publish:
    name: Helm
    uses: bakdata/ci-templates/.github/workflows/helm-multi-release.yaml@1.69.2
    needs: get-version
    with:
      charts-path: "charts"
      subdirs: "['cnpg-database']"
      version: ${{ needs.get-version.outputs.version }}
    secrets:
      github-username: ${{ secrets.GH_USERNAME }}
      github-email: ${{ secrets.GH_EMAIL }}
      github-token: ${{ secrets.GH_TOKEN }}
